data_path: /home/nate/data/DTU/
points_data_path: #/mnt/Drive1/Results/DTU/MVSNet/Points
output_path: /mnt/Drive1/Results/DTU/2DGS/
device: cuda:0
seed: 43
num_workers: 4

camera:
  height: 1200
  width: 1600
  near: 425
  far: 937
  crop_h: 48
  crop_w: 64

inference:
  scale: 1.0

loss:
  dist_iter: 3000
  dist_weight: 0.0
  dssim_weight: 0.2
  normal_iter: 7000
  normal_weight: 0.05

model:
  sh_degree: 3
  white_background: False

optimization:
  ckpt_freq: -1
  densification_interval: 100
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  feature_lr: 0.0025
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  opacity_th: 0.05
  rotation_lr: 0.001
  scaling_lr: 0.005

rendering:
  maps: ['RGB', 'Alpha', 'Normal', 'Depth', 'Edge', 'Curvature']

visualization:
  ip: "127.0.0.1"
  max_depth_error: 5.0
  port: 6009
