data_path: /home/nate/data/DTU/
points_data_path: /mnt/Drive1/Results/DTU/MVSNet/
output_path: /mnt/Drive1/Results/DTU/2DGS/
device: cuda:0
seed: 43
num_workers: 4

camera:
  height: 1200
  width: 1600
  near: 425
  far: 937
  crop_h: 48
  crop_w: 64
  baseline_mode: min

inference:
  ckpt_file: pretrained_models/GBiNet/DTU/model.pt
  frame_spacing: 1
  num_frame: 5
  sample_mode: cluster
  scale: 1.0
  visualize: True
  vis_freq: 1

loss:
  dist_iter: 3000
  dist_weight: 0.0
  dssim_weight: 0.2
  normal_iter: 7000
  normal_weight: 0.05
  res_weights: [1,1,1,1]

mvs_model:
  feature_channels: [64,32,16,8] # coarse -> fine
  group_channels: [8,8,8,4] # coarse -> fine
  stage_ids: [0,0,1,1,2,2,3,3] # coarse -> fine
  confidence_iterations: 6 # number of iterations to accumulate confidence

gs_model:
  sh_degree: 3
  white_background: False

optimization:
  ckpt_freq: -1
  densification_interval: 100
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  feature_lr: 0.0025
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  opacity_th: 0.05
  rotation_lr: 0.001
  scaling_lr: 0.005

rendering:
  maps: ['RGB', 'Alpha', 'Normal', 'Depth', 'Edge', 'Curvature']

training:
  batch_size: 4
  ckpt_file: 
  epochs: 30
  frame_spacing: 1
  grad_clip: 10.0
  learning_rate: 0.0001
  lr_steps: 10,12,14
  lr_gamma: 0.50
  max_training_samples: 5000
  max_val_samples: 1000
  num_frame: 5
  random_crop: True
  sample_mode: cluster
  scale: 0.5
  visualize: True
  vis_freq: 100

visualization:
  ip: "127.0.0.1"
  max_depth_error: 5.0
  port: 6009
