data_path: /home/nate/data/DTU/
output_path: /mnt/Drive1/Results/DTU/2DGS_2/
points_path: /mnt/Drive1/Results/DTU/NP_CVP_MVSNet/Points
voxel_size: 0.3
device: cuda:0
seed: 43
num_workers: 4

camera:
  height: 1200
  width: 1600
  near: 425
  far: 937
  crop_h: 0
  crop_w: 0

inference:
  scale: 1.0

loss:
  dist_iter: 3000
  dist_weight: 0.0
  dssim_weight: 0.2
  normal_iter: 7000
  normal_weight: 0.05

model:
  sh_degree: 3
  white_background: False

optimization:
  ckpt_freq: 10000
  densification_interval: 100
  densify_from_iter: 500
  densify_grad_threshold: 0.0002
  densify_until_iter: 15000
  feature_lr: 0.0025
  iterations: 30000
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 0.0000016
  position_lr_init: 0.00016
  position_lr_max_steps: 30000
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  opacity_th: 0.05
  rotation_lr: 0.001
  scaling_lr: 0.005

point_cloud:
  pix_th: 0.40
  prob_th: 0.80
  num_consistent: 3
  mask_th: 20
  max_dist: 0.5
  min_dist: 0.0
  min_point_dist: 0.03 # use 0.2 (0.03) with sparse (dense) GT point clouds
  resolution: dense # OPTIONS: [sparse, dense]

rendering:
  frames: 360
  iteration: -1 # gaussian model iteration to load
  maps: ['RGB', 'Alpha', 'Normal', 'Depth', 'Edge', 'Curvature']
  video_maps: ["rendered_image", "normal", "depth", "opacity"]

visualization:
  ip: "127.0.0.1"
  max_depth_error: 5.0
  port: 6009
